version: 2.1
jobs:
  TWRP-spes:
   docker:
      - image: iaboothahir/docker:Twrp-build
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir twrp && cd twrp
            repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
            repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j$(nproc --all)
            git clone https://github.com/shashankx86/android_device_xiaomi_spes-TWRP.git -b twrp-11 device/xiaomi/spes
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/twrp
            export ALLOW_MISSING_DEPENDENCIES=true
            source build/envsetup.sh
            lunch twrp_spes-eng
            mka bootimage
      - run:
          name: Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/twrp/out/target/product/spes
            ZIPNAME="TWRP-$(date +%d_%m_%Y_%H_%M)-X00TD.zip"
            sudo zip -r9 $ZIPNAME *.img
            curl -sL $OUTFILE https://git.io/file-transfer | sh
            ./transfer wet .
workflows:
  version: 2.1
  cooking:
    jobs:
      - TWRP-spes